README.md
Changes the README to recommend setting a local override, rather than setting the default toolchain. Also removes some leftover whitespace
=> Don't recommend setting default rust toolchain

examples/cross-contract-high-level/.cargo/config, examples/cross-contract-high-level/Cargo.lock, examples/cross-contract-high-level/build.sh, examples/cross-contract-low-level/.cargo/config, examples/cross-contract-low-level/Cargo.lock, examples/cross-contract-low-level/build.sh, examples/fun-token/.cargo/config, examples/fun-token/Cargo.lock, examples/fun-token/build.sh, examples/mission-control/.cargo/config, examples/mission-control/Cargo.lock, examples/mission-control/build.sh, examples/status-message-collections/.cargo/config, examples/status-message-collections/Cargo.lock, examples/status-message-collections/build.sh, examples/status-message/.cargo/config, examples/status-message/Cargo.lock, examples/status-message/build.sh
(otherwise the .wasm file might be too large to deploy)
=> Update build command in build.sh to ensure optimized build

README.md
Very simple clean-up of some anchor links in the README that pointed to a couple sections removed in this commit:
https://github.com/nearprotocol/near-bindgen/commit/61b0ef92326663fdc9fe43be50afea46f87ba2ab#diff-04c6e90faac2675aa89e2176d2eec7d8L251
=> remove readme anchor links to outdated Running & Limitations sections

.travis.yml
@nearmax It seems a bug that travis didn't trigger for master branch. Remove only: master to see if it runs for master
=> Remove only branch is master for now

contact-builder/run.sh
Use $HOST_DIR to be able to use it for other projects. E.g. core-contracts
=> Update contract builder run to use HOST_DIR

near-sdk-core/Cargo.toml, near-sdk-macros/Cargo.toml
Seems like `<=` doesn't actually restrict `borsh` from depending on the `syn = "1.0.60"`
Switching to `=1.0.57`
Verified that is fixes the issue.
=> Fix `syn` crate pin using `=1.0.57` instead of `<=1.0.57`

examples/fungible-token/README.md
I made this change in https://github.com/near-examples/FT and figured I'd backport it here since it's useful for both.
=> examples/ft: small readme improvement

examples/fungible-token/tests/general.rs
The project structure makes this superfluous
=> refactor(examples/ft): no need for `extern crate`

examples/fungible-token/Cargo.toml, examples/fungible-token/examples/heavy.rs, near-sdk-sim/Cargo.toml, near-sdk-sim/src/cache.rs, near-sdk-sim/src/lib.rs, near-sdk-sim/src/runtime.rs, near-sdk-sim/src/user.rs
After Contracts compile they are cached at `target/contract_cache/<Hash>`.
Adds an example for a sample program that does a transfer back and forth in order to test the performance.
=> feat: add contract caching in simulation testing

near-contract-standards/src/fungible_token/core_impl.rs, near-contract-standards/src/fungible_token/storage_impl.rs
Currently, we are receiving just _"The account is not registered"_ error when there's no registered account and these functions of FT are called:
* `FungibleToken::internal_deposit()`
* `FungibleToken::internal_withdraw()`
* `StorageManagement::storage_deposit()`
* `StorageManagement::storage::withdraw()`
This is not very convenient and could be sometimes not that easy to find out (especially having complex contracts with cross-contracts calls) which account doesn't exist indeed. We recently ran into this problem when writing some sim tests and spent a lot amount of time trying to track the issue. Making these messages more descriptive by specifying the account id solves the issue.
=> FungibleToken: improve error messages for non-registered accounts

README.md
Can't do relative links to directories
=> Fix broken link to contract-builder

near-contract-standards/src/fungible_token/core_impl.rs
When implementing contracts which operate with fungible tokens, it's useful to use `#[ext_contract(ext_fungible_token)]` macro.
This PR adds a canonical implementation of that wrapper to near-contract-standards.
=> contract standards: add ext_fungible_token

near-contract-standards/src/fungible_token/storage_impl.rs
Fixes #342
Multiple people, me included, have been confused on their first read of this function. To save future readers from confusion, let's add a comment explaining why this implementation is correct.
=> docs(contract-standards): add clarifying comment

near-sdk/src/json_types/public_key.rs
- Implements FromStr for `CurveType` and `Base58PublicKey`
- Switches deserialization intermediate type to `Cow`
- Document type (was unclear to me what exactly was supported)
=> feat(json_types): impl FromStr for public key json types and cleanup

near-sdk/src/collections/unordered_map.rs, near-sdk/src/collections/unordered_set.rs
This just makes this code more readable
=> refactor(collections): remove unnecessary explicit lifetimes from unordered types

near-sdk/src/collections/legacy_tree_map.rs, near-sdk/src/collections/tree_map.rs
In the case of lo > hi and both are excluded, this does not panic as the function comment suggests.
If this is intended, let me know and I can update the docs or add docs on the `Cursor` to indicate it will panic in this case (if it does).
=> fix(collections): range panic on lo/hi excluded and flipped

near-sdk/src/json_types/account.rs
Just saw https://stackoverflow.com/questions/67332443/how-to-convert-accountid-into-validaccountid-in-near-protocol-contracts
and this makes it easier to convert as it doesn't require importing the `TryFrom` or `TryInto` trait
Also changes the logic a bit to avoid allocating a `String` from `&str` before it's checked as valid.
=> feat(json_types): implement FromStr for ValidAccountId

.github/workflows/test.yml, Cargo.toml, near-sdk/tests/code_size.rs
cc @matklad as he suggested adding these before making other changes/refactoring.
The tests compile to wasm using release and any other usual flags and check the output wasm binary size.
The test checks to make sure it's no larger than 10% of what it currently is, to accommodate for external/platform discrepancies. Still feels a bit janky to me to test like this personally, but seems like it might be a reasonable check to have.
=> feat: add compiled code size tests

examples/fungible-token/tests/sim/utils.rs, near-sdk-sim/src/user.rs
- Allows trailing comma on the `deploy!` macro, which is in line with rustfmt for multiline style guide
related #420
=> feat(simulator): allow trailing comma on simulator deploy macro

CHANGELOG.md, README.md
- Removes release notes from README to remove clutter
- Adds unreleased changes to changelog
- This only includes changes that would be relevant to SDK users, but I am open to updating any format or including all changes
- Adds date to releases.
- this can be useful for users to easily check what has changed since they last used it or know how mature a release is
Please share any options on how this should be structured, as it would be best if this has a format we're all happy with to keep this up to date. I considered having crate level `CHANGELOG`s but decided against it because there wasn't a need for that granular of changes it seems.
=> chore: remove release notes from README and add unreleased changes to CHANGELOG

ci-test.sh
When attempting to run the `ci-test.sh` script, the use of `sed` has an issue on OS X.
After reading this article:
https://ed.gs/2016/01/26/macos-sed-invalid-command-code
found that this small modification will allow it to run locally. It looks like this change is only additive and linux systems (used for CI) shouldn't have an issue with it.
=> Modify ci-test script so it can be run on OS X

near-sdk/src/environment/env.rs
cc @mikedotexe as you mentioned this would be useful for testing, and I would generally agree given it doesn't have negative side effects I'm not aware of.
I've kept the config as restrictive as possible so this never gets compiled in release mode or if in wasm32 arch, but can remove the release check if that's wanted.
=> feat: Print logs when in debug and not wasm32 architecture

near-contract-standards/src/fungible_token/macros.rs, near-contract-standards/src/non_fungible_token/macros.rs
Possibly this should also be included before #436 comes in and released. Noticed when scanning over changes
=> fix: crate references in contract-standards macros

Cargo.lock, near-contract-standards/Cargo.toml
Dry run went successful, will publish when confirmed and update anything here if necessary.
(release only contains NFT standard)
=> chore: bump contract standards version for release

CHANGELOG.md, examples/mission-control/src/mission_control.rs, examples/test-contract/src/lib.rs, near-sdk/src/environment/env.rs, near-sdk/src/environment/mocked_blockchain.rs
Made changes based on #417 because it removes `BLOCKCHAIN_INTERFACE` from non-wasm32 environments, and this default only makes sense outside anyway.
One part of #440, going to split up changes because other ideas I have are more opinionated/breaking.
This change is completely backwards compatible from #417 and I changed only some of the examples to show this.
Ideally, in the future, it would be possible to modify the context of the mocked blockchain in place instead of still rigidly constructing a new context and replacing the current one, which will come with more QOL improvements.
=> feat: Initialize blockchain interface by default

near-sdk/src/json_types/mod.rs
Just to stay consistent with #464, added the deprecated attribute to `ValidAccountId`
=> Add deprecated ValidAccountId type mentioned in #464

CHANGELOG.md, near-sdk/src/environment/env.rs, near-sdk/src/environment/sys.rs
A better interface when interacting with syscalls directly avoids using `unreachable` in `env`
Also, side note, I've never understood why we don't expose a public `env::panic` to avoid having to log a message if a developer doesn't want to? Is it just to discourage this or push people toward using `unreachable` or a similar panic?
=> fix: update panic signature to indicate no return

CHANGELOG.md, Cargo.lock, examples/cross-contract-high-level/Cargo.lock, examples/cross-contract-low-level/Cargo.lock, examples/fungible-token/Cargo.lock, examples/gas-fee-tester/Cargo.lock, examples/lockable-fungible-token/Cargo.lock, examples/mission-control/Cargo.lock, examples/non-fungible-token/Cargo.lock, examples/status-message-collections/Cargo.lock, examples/status-message/Cargo.lock, examples/test-contract/Cargo.lock, near-contract-standards/Cargo.toml, near-sdk-macros/Cargo.toml, near-sdk-sim/Cargo.toml, near-sdk-sim/README.md, near-sdk/Cargo.toml, near-sdk/src/collections/legacy_tree_map.rs, near-sdk/src/types/account_id.rs, near-sdk/src/utils/mod.rs
- Bumped versions to `4.0.0-pre.1`
- Fixed broken doc links
Changes since last release: https://github.com/near/near-sdk-rs/compare/bac0ec71395c93620b215573bbaf5a4e4a9b8e85...austin/4_release
Will do a pass through to make sure nothing else needs to get cleaned up before releasing
=> chore: bump versions for 4.0.0-pre.1 release and cleanup

near-sdk/src/environment/mock/mocked_blockchain.rs
Interface was changed in #489 but the mock implementation didn't indicate the same with the function not returning. I don't think this has any affect on anything, but probably safe to make sure these match.
The panic calls to VM logic always error and that gets unwrapped, which is why unreachable
=> fix: mock sys interface panic signature

near-contract-standards/src/fungible_token/core_impl.rs, near-contract-standards/src/non_fungible_token/approval/approval_impl.rs, near-contract-standards/src/non_fungible_token/core/core_impl.rs, near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/info_extractor/mod.rs, near-sdk-sim/src/outcome.rs, near-sdk-sim/src/runtime.rs, near-sdk-sim/src/user.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/bad_argument.stderr, near-sdk/compilation_tests/metadata_invalid_rust.stderr, near-sdk/src/collections/lazy_option.rs, near-sdk/src/collections/legacy_tree_map.rs, near-sdk/src/collections/lookup_map.rs, near-sdk/src/collections/tree_map.rs, near-sdk/src/collections/unordered_map.rs, near-sdk/src/collections/vector.rs, near-sdk/src/promise.rs, near-sdk/src/types/account_id.rs, near-sdk/src/types/public_key.rs
Self explanatory, new clippy version comes with some new enforced lints.
Also TIL about:
```bash
cargo +nightly clippy --fix -Z unstable-options --allow-dirty -- -Dclippy::all
```
When I was being impatient
=> chore: fix new clippy warnings

CHANGELOG.md, near-sdk/src/environment/mock/external.rs, near-sdk/src/environment/mock/receipt.rs
This was ported from internally, so missed that this is in fact an account id from #479.
Also removes some irrelevant docs
=> fix(mock): receiver id on receipt to be AccountId

near-sdk/src/types/primitives.rs
When I was reading the docs for Promises, I wasn't sure at first if `transfer` accepted yoctoNEAR or NEAR. This gives people a way to click through to `Balance` and find out.
Documenting it on `Balance` rather than `transfer` also means they'll be able to verify anywhere they encounter a `Balance` in the docs.
=> docs: specify that Balance is yoctoNEAR

CHANGELOG.md, near-sdk/src/environment/mock/external.rs, near-sdk/src/environment/mock/receipt.rs
Noticed this was off when looking around. Method names throughout the sdk are strings, so this should be also.
=> fix(mock): method names type within receipts to be Strings

near-contract-standards/src/non_fungible_token/core/core_impl.rs
Fixes #594 
Removed the comment that stated only the owner could mint in the NFT struct.
=> Changed comment for the owner_id field in the NFT struct

near-sdk/src/utils/mod.rs
Closes #597 
No need for a feature, since you can enable debug assertions, even if you want it in release mode
=> feat: use rust assertions in require! debug for line numbers

README.md
Closes #601 
Probably should update these docs at some point, because the quickest way to get reproducible builds is using the prebuilt image
=> fix(readme): contract-builder link

near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs
Closes #615 
Probably rare someone would want to modify this structure in place for a view method, which is probably how this wasn't hit before, but good to have this functional
=> fix: code generation for mut self methods

near-contract-standards/src/storage_management/mod.rs
Currently, only serialization is allowed for `StorageBalance` and `StorageBalanceBounds`. This means that we cannot use the result returned from `storage_deposit`, `storage_withdraw`, `storage_balance_bounds` and `storage_balance_of` since we cannot deserialize it.
Ex: the following will result in a compilation error
`near_sdk::serde_json::from_slice::<StorageBalance>(&result).unwrap();` where `result` is the result returned by `storage_balance_of`.
=> Allow deserialization for StorageBalance and StorageBalanceBounds

near-sdk/src/environment/hash.rs
Helper function was only needed when there were more steps, not needed now as it somewhat hides the unsafety constraints of the operations. Added the safety docs as well to describe why this is safe.
=> refactor: Remove helper function and add safety docs

CHANGELOG.md, near-sdk-sim/src/runtime.rs, near-sdk-sim/src/user.rs, near-sdk/src/environment/env.rs, near-sdk/src/environment/mock/external.rs, near-sdk/src/environment/mock/mocked_blockchain.rs, near-sdk/src/environment/mock/receipt.rs, near-sdk/src/promise.rs, sys/src/lib.rs
inline with https://github.com/near/docs/issues/905, naming within the SDK is mixed, even within the same function, so this changes method terminology to function.
This should only be a breaking change for mock receipts, others are all positional and I don't think the promise enums are exposed in any way, which I will follow up on now. (They were private)
=> fix: consistent naming to only using function over method

near-sdk/src/store/lazy/mod.rs
This is only new collection type which this hasn't been updated yet. Doesn't change anything with the API and only saves 8 bytes on the structure (prefix never needs to be variable length)
=> fix: update storage key type to be boxed slice for Lazy storage

.github/workflows/test.yml
MSRV is only this high because new nearcore crates use the 2021 edition, which requires 1.56
=> chore: add msrv check to CI

CHANGELOG.md, near-sdk/src/store/lookup_map/mod.rs, near-sdk/src/store/lookup_set/impls.rs, near-sdk/src/store/lookup_set/mod.rs, near-sdk/src/store/mod.rs
Closes #586 
The interface matches `std::collections::HashSet` without the functions that require being aware of all values in the set. The implementation relies on `LookupMap` for all the heavy lifting.
=> feat: caching LookupSet implementation

CHANGELOG.md, near-sdk/src/store/lookup_map/mod.rs, near-sdk/src/store/lookup_set/impls.rs, near-sdk/src/store/lookup_set/mod.rs
Closes #659
This PR re-implements `LookupSet` so that it tracks all elements by itself and only uses `env::storage_write` with an empty array of bytes and `env::storage_has_key` as opposed to `env::storage_read` (which is more expensive).
=> feat(store): Re-implement LookupSet in a more efficient manner

near-sdk/src/store/free_list/mod.rs, near-sdk/src/store/unordered_map/mod.rs
Was needed before `drain`, this is redundant now and could lead to unnecessary CPU cycles.
=> fix(unordered_map): remove unnecessary clear call

near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs
Rust 1.58 comes with some new clippy lints, which seems to include removing unnecessary `to_string` calls within macros.
=> fix: clippy warnings from new version

near-contract-standards/src/fungible_token/core_impl.rs
not sure whether it was a "must return "0"" or "returns "0"" so correct if wrong
=> fix a typo in a comment

near-sdk/tests/code_size.rs
self-explanatory, CI is failing in other branches rn
=> fix: new clippy warning from 1.59

CHANGELOG.md, near-sdk-macros/src/core_impl/code_generator/attr_sig_info.rs, near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs, near-sdk-macros/src/core_impl/mod.rs, near-sdk-macros/src/core_impl/utils/mod.rs, near-sdk-macros/src/lib.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/function_error.rs, near-sdk/src/lib.rs, near-sdk/src/types/error.rs, near-sdk/src/types/mod.rs
Fixes #574 
This PR provides an opt-in way to treat `Result` function return types as an error-handling mechanism. Meaning that only the underlying `Ok` values are serialized while the `Err` values result in panic. To do this, `FunctionError` must be implemented by the `Err`type (there are default implementations for types that have `Borrow<str>` and a derivation macro that generates a `ToString`-powered implementation).
The legacy behavior still works by default (`Result` is treated as a normal value and goes through full serialization), but it is supposed to generate compilation warnings (I am still trying to figure out a proper way to do this as`compile_warning!` seems to be missing rn, any suggestions are welcome). The user will have to mark the function with `#[return_result]` to …
=> feat: add an optional way to handle contract errors with `Result`

CHANGELOG.md
Didn't notice the format didn't match to link to the changes at the bottom
=> fix: changelog links

CHANGELOG.md, near-sdk/src/collections/mod.rs, near-sdk/src/collections/unordered_map/iter.rs, near-sdk/src/collections/unordered_map/mod.rs
Made the change minimally invasive since this is somewhat of a legacy collection. The new ones are optimized and I assumed that `zip` with the optimization done to #634 would be applied to the `UnorderedMap`, but it wasn't.
exposes `unordered_map` module to allow `Iter` type to be used. Didn't add iterator types to others since no demand. There would be a benefit (in that the aux iterator traits would be available) but I don't want to return `vector::Iter` for backwards compatibility if we wanted to switch later and didn't want to just add a bunch of redundant code for no strong reason.
=> fix: Optimize nth implementation for legacy UnorderedMap

contract-builder/Dockerfile
1.60 is needed to be able to build the nearcore crates used for unit testing after #820 as can be seen from this failed buildkite https://buildkite.com/nearprotocol/near-sdk-rs/builds/4076#090f7030-7abe-48bf-80a0-95fbce8f323f
This adds more value to https://github.com/near/near-ops/issues/839 since using `latest` and bumping people's images based on this for updates like this isn't a good pattern. cc @anshal-savla 
Also noting that changes like this would break old CI runs on this repo since the toolchain is different and would produce different binaries -- there should be a way to specify the Rust toolchain version on the image tag
=> chore: bump contract builder to version 1.61

near-contract-standards/src/fungible_token/metadata.rs
Currently, users building smart contracts can use  `ext_ft_core` to make cross-contract calls to Fungible token methods enumerated in NEP-141. However, to make a call to the `ft_metadata` method, they have to define their own trait in their smart contract because `FungibleTokenMetadataProvider` does not have a `ext_contract` macro. This PR adds the `ext_contract` macro to the `FungibleTokenMetadataProvider` trait so that users do not have to copy/paste this trait into their code.
=> Add ext_contract macro to FungibleTokenMetadataProvider trait

.github/workflows/test.yml
Ignoring time audit vulnerability because it isn't exposed through chrono, which is what `nearcore` crates pull this in through
https://github.com/chronotope/chrono/issues/602
=> chore: add audit to SDK CI

examples/callback-results/Cargo.lock, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.lock, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.lock, examples/factory-contract/Cargo.toml, examples/fungible-token/Cargo.lock, examples/fungible-token/Cargo.toml, examples/lockable-fungible-token/Cargo.lock, examples/lockable-fungible-token/Cargo.toml, examples/non-fungible-token/Cargo.lock, examples/non-fungible-token/Cargo.toml
This patch version fixes the non-determinism in our CI failures (which is starting to get annoying)
=> chore: bump workspaces version to new patch

CHANGELOG.md, near-contract-standards/src/lib.rs
Not quite sure why this was added, somewhat broken as per #855 and the interface doesn't make much sense and is inefficient.
Deprecating for now and can optimize/update if there are real use cases or the standard is actually added to NEPs
=> chore: deprecate upgrade standards implementation

near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/utils/mod.rs
Forgot to extract the underlying type from `Vec<_>` for ABI
=> fix: extract #[callback_vec] vec type for abi

near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs
Fixes https://github.com/near/near-sdk-rs/issues/853
=> fix: support `#[handle_result]` in ABI macro

CHANGELOG.md, examples/abi/Cargo.lock, examples/callback-results/Cargo.lock, examples/cross-contract-calls/Cargo.lock, examples/factory-contract/Cargo.lock, examples/fungible-token/Cargo.lock, examples/lockable-fungible-token/Cargo.lock, examples/mission-control/Cargo.lock, examples/non-fungible-token/Cargo.lock, examples/status-message-collections/Cargo.lock, examples/status-message/Cargo.lock, examples/test-contract/Cargo.lock, examples/versioned/Cargo.lock, near-sdk/Cargo.toml
The intention is to have it matched with workspaces to avoid duplicate deps (https://github.com/near/workspaces-rs/issues/171)
=> chore: bump nearcore crates to 0.14

near-sdk-macros/src/core_impl/abi/abi_generator.rs
The current code does not work for some types e.g. `()::schema_container()` vs `<()>::schema_container()`
=> fix: wrap `$ty` in angle brackets for ABI macro

CHANGELOG.md, near-sdk/Cargo.toml, near-sdk/src/environment/mock/mocked_blockchain.rs
It's been stabilized, so devs will need this to test
=> feat: Support newly stabilized alt_bn128 host functions

ci-test.sh, examples/abi/Cargo.lock, examples/callback-results/Cargo.lock, examples/cross-contract-calls/Cargo.lock, examples/factory-contract/Cargo.lock, examples/fungible-token/Cargo.lock, examples/lockable-fungible-token/Cargo.lock, examples/mission-control/Cargo.lock, examples/non-fungible-token/Cargo.lock, examples/status-message-collections/Cargo.lock, examples/status-message/Cargo.lock, examples/test-contract/Cargo.lock, examples/versioned/Cargo.lock
The check flag just ensures no git changes during building examples. Was removed when trying to avoid checking wasm file changes, but those files were removed, so can add the check back to make sure no hidden lockfile changes.
Pointed out in https://github.com/near/near-sdk-rs/pull/889#discussion_r951630977
=> fix: Add back git diff check into CI

near-sdk/src/collections/mod.rs, near-sdk/src/store/index_map.rs, near-sdk/src/store/lazy/mod.rs, near-sdk/src/store/lazy_option/impls.rs, near-sdk/src/store/lazy_option/mod.rs, near-sdk/src/store/lookup_map/mod.rs, near-sdk/src/store/lookup_set/mod.rs, near-sdk/src/store/mod.rs, near-sdk/src/store/tree_map/mod.rs, near-sdk/src/store/unordered_map/mod.rs, near-sdk/src/store/unordered_set/mod.rs, near-sdk/src/store/vec/mod.rs
Fixes some comments through this review (https://github.com/near/near-sdk-rs/pull/815#pullrequestreview-1083761194) and some others I think that can be improved.
~~The only functional change is the change of the field name of the storage prefix in `LazyOption`. unclear why this one was set as different. Shouldn't break any APIs, but changes the debug impl~~
=> chore: update docs for `Vector` and `store` collections

near-sdk/Cargo.toml
a patch release was made that breaks with 1.61 so our buildkite CI was broken. Temporary workaround
=> chore: restrict arbitrary version

near-sdk/src/store/lazy/impls.rs, near-sdk/src/store/lazy/mod.rs, near-sdk/src/store/lazy_option/impls.rs, near-sdk/src/store/lazy_option/mod.rs
Noticed when working on related things that these were not matching. This should be resolved before #888 comes in, but is a separate issue
What this proposes is including the cached value in debug output but keeping the type as an `Option` so that we can change the implementation without breaking this format. Can alternatively just keep the default debug derive or ignore cache, but the cache seems important for debug purposes. (Maybe not obfuscating the cache entry type is valuable to see if a value has been flushed to storage)?
=> fix: Make Lazy and LazyOption debug impls match

near-sdk-macros/src/core_impl/abi/abi_embed.rs
Before
```console
$ cargo check --all-features
error: environment variable `CARGO_NEAR_ABI_PATH` not defined
--> near-sdk-macros/src/core_impl/abi/abi_embed.rs:5:20
|
5 |     let abi_path = env!("CARGO_NEAR_ABI_PATH");
|                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
error: could not compile `near-sdk-macros` due to previous error
```
Now, the only time this error comes up is when all three of these conditions are true:
1. You're building something that invokes the `#[near_bindgen]` attribute.
2. You have the `near-sdk/__abi-embed` feature flag activated.
3. The `CARGO_NEAR_ABI_PATH` env is unset.
And as far as the flow with `cargo near` is well-defined, this should never …
=> fix: cargo check with all features

examples/fungible-token/ft/Cargo.toml, examples/fungible-token/test-contract-defi/Cargo.toml
Seems like we have missed a couple of them
=> chore: remove rlib from examples

near-contract-standards/Cargo.toml
I noticed through https://github.com/near/near-sdk-rs/issues/910#issuecomment-1232939216 that these optional features aren't disabled by default by contract-standards, so someone could not disable these default features AND use `near-contract-standards`. oops!
=> fix: remove default features from SDK dependency on standards

near-sdk/src/json_types/hash.rs, near-sdk/src/json_types/integers.rs, near-sdk/src/json_types/vector.rs, near-sdk/src/types/gas.rs, near-sdk/src/types/public_key.rs
Tested ABI flow on a few external contracts and one of them was exposing `PublicKey`, so I think it makes sense to implement `JsonSchema` for all newtypes that already derive `(De)serialize`.
Also fixed a bug with large integer schemas - they are serialized as strings, but the automatic `JsonSchema` derivation makes them look as if they are numbers.
=> chore: impl `JsonSchema` for newtypes

CHANGELOG.md, near-sdk/src/json_types/hash.rs
Noticed when looking at https://github.com/near/near-sdk-rs/issues/399 that the error type hadn't been updated for the other parsing methods, only `FromStr`. Yes, this is a breaking change, but it should not affect any usages of this type in practice and it will be coming with a minor version bump.
closes #399
=> fix: update Base58 parsing error

CHANGELOG.md, near-sdk/src/store/index_map.rs, near-sdk/src/store/lookup_map/mod.rs, near-sdk/src/store/mod.rs, near-sdk/src/store/vec/mod.rs, near-sdk/src/utils/stable_map.rs
Part of #818 
These two are already documented thoroughly and have been tested a lot
=> chore: stabilize `store::LookupMap` and `store::UnorderedMap`

near-sdk-macros/src/lib.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/borsh_storage_key_generics.rs
Tried to use a reference for this today, but realized this isn't supported.
=> feat: allow generics for borsh storage key derive

examples/adder/.cargo/config.toml, examples/adder/build.sh, examples/callback-results/.cargo/config.toml, examples/callback-results/build.sh, examples/cross-contract-calls/.cargo/config.toml, examples/cross-contract-calls/build.sh, examples/factory-contract/.cargo/config.toml, examples/factory-contract/build.sh, examples/fungible-token/.cargo/config.toml, examples/fungible-token/build.sh, examples/lockable-fungible-token/.cargo/config.toml, examples/lockable-fungible-token/build.sh, examples/mission-control/.cargo/config.toml, examples/mission-control/build.sh, examples/non-fungible-token/.cargo/config.toml, examples/non-fungible-token/build.sh, examples/status-message-collections/.cargo/config.toml, examples/status-message-collections/build.sh, examples/status-message/.cargo/config.toml, examples/status-message/build.sh, examples/test-contract/.cargo/config.toml, examples/test-contract/build.sh, examples/versioned/.cargo/config.toml, examples/versioned/build.sh
Not sure if there is a reason not to share the target directory across all examples. This saves ~35% of disk space on a clean build (1.7GB vs 2.6GB).
=> chore: make examples use the root target folder

.github/workflows/test.yml, CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml, near-sdk/src/lib.rs
closes #869
This doesn't functionally change anything because it's enabled by default, but allows devs to remove this section, and this will be deprecated in the next major version
=> chore: put legacy collections under feature flag

near-sdk/Cargo.toml
A minor release was cut that requires a MSRV of `1.63` so our buildkite CI was broken. Temporary workaround.
Associated CI: https://buildkite.com/nearprotocol/near-sdk-rs/builds/4465#0183f87e-2f41-4fec-ad5b-e068e8f67205
=> chore: pin version of derive_arbitrary

near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk/Cargo.toml
`cargo-near` + `near-sdk`, at any point in time, could use versions of `near-abi` with conflicting in-memory representations of `ChunkedAbiEntry`, making it impossible to simply cast one as the other.
Since `near-abi` already hosts a deserialization implementation for `ChunkedAbiEntry`, with `schema_version` validation, it makes sense to just use that.
This means the ABI chunk generator has to return a JSON string directly, which `cargo-near` can then parse, returning a neat error if an error occurred.
This is linked to https://github.com/near/cargo-near/pull/74.
=> feat: return raw bytes from ABI chunk generators

near-sdk/src/types/vm_types.rs
noticed this when doing #948 but separated from those changes because this isn't as breaking and can come in 4.1
I think these aliases might have been used previously, otherwise, I don't know why these weren't removed before.
=> chore: deprecate vm logic types

near-sdk/compilation_tests/cond_compilation.rs
The `#[near_bindgen]` macro currently ignores tokens after the attribute name, for example `#[near_bindgen(this_is_ignored)]`. This is due to `_attr` (which [contains these tokens](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros)) being ignored:
https://github.com/near/near-sdk-rs/blob/039cc110c9c01907b95250a50d9ff8ccbad99cbf/near-sdk-macros/src/lib.rs#L46-L47
There's a contract used in compilation test which has tokens after the attribute name: `#[near_bindgen(init => new)]`. They are removed in this PR.
For [`near-plugins`](https://github.com/aurora-is-near/near-plugins) we're experimenting with passing extra tokens like `#[near_bindgen(some_config(value_a, value_b))]`. When adding logic to parse these tokens via …
=> Remove unused tokens in compilation test

near-sdk/src/collections/unordered_map/mod.rs, near-sdk/src/json_types/vector.rs, near-sdk/tests/code_size.rs
The [skip optimization I added to Rust](https://github.com/rust-lang/rust/pull/96350) has been released with 1.65 and broke one of our test vectors.
=> fix: update test vector for optimized skip

examples/adder/Cargo.lock, examples/adder/Cargo.toml, examples/adder/res/adder_abi.json, examples/adder/src/lib.rs, examples/fungible-token/Cargo.lock, near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk/Cargo.toml, near-sdk/src/private/mod.rs
Related: https://github.com/near/cargo-near/pull/83
=> chore: use near-abi 0.3.0

examples/adder/Cargo.toml, examples/callback-results/Cargo.lock, examples/cross-contract-calls/Cargo.lock, examples/factory-contract/Cargo.lock, examples/fungible-token/ft/Cargo.toml, examples/fungible-token/test-contract-defi/Cargo.toml, examples/lockable-fungible-token/Cargo.lock, examples/mission-control/Cargo.lock, examples/non-fungible-token/Cargo.lock, examples/status-message-collections/Cargo.lock, examples/status-message/Cargo.lock, examples/test-contract/Cargo.lock, examples/versioned/Cargo.lock, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
According to our previous discussion of the matter, it seems like there is no benefit of having this not enabled by default. We have also seen that this seems to be a friction point for some people.
=> feat: make `abi` a default feature

near-sdk-macros/src/core_impl/code_generator/ext.rs
As mentioned in [this comment](https://github.com/near/near-sdk-rs/pull/952#pullrequestreview-1165458157), non-bindgen attributes on `Contract` methods shouldn't be forwarded to `ContractExt` methods.
In some cases it might lead to compilation errors or unintended behavior, see #952 for example.
**Note**: I assume technically that's a breaking change - but then, it's hard to think of a case where contract developers want these attributes to be forwarded (besides `cfg`).
=> Stop forwarding all non-bindgen attributes to _Ext methods

README.md
There were a few issues to be closed relating to the README, so I figured I'd just do them.
Rendered https://github.com/near/near-sdk-rs/blob/austin/readme-update/README.md
closes #405 
closes #384
closes #246 
- Update badge to gh actions (was bugging me that buildkite badge was borked)
- Fix links
- Include build information, linking to cargo-near
=> chore: update readme to include versioning and fixes

near-contract-standards/src/non_fungible_token/enumeration/enumeration_impl.rs
When the user's `token_set` is empty this method panics now in case of use
```
{
...
from_index: None,
limit: None,
}
```
But i propose for an empty list returned in this situation
=> Fix empty owner tokens `start_index` error

flake.lock, flake.nix, near-contract-standards/src/fungible_token/core_impl.rs, near-contract-standards/src/non_fungible_token/core/core_impl.rs, near-sdk-macros/src/core_impl/code_generator/attr_sig_info.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs, near-sdk/src/environment/env.rs, near-sdk/src/types/vm_types.rs
It can't be generated by the runtime fixes #796
=> Removed the not ready enum type

near-sdk/src/environment/env.rs, near-sdk/src/lib.rs, near-sdk/src/promise.rs
Address's #871 .
I expect this is a reasonable final state for the library, but how should I manage the migration?
Create new function names for the new behavior and depreciate the old endpoints?
=> Took out a footgun with allowances

near-sdk/src/store/tree_map/iter.rs, near-sdk/src/store/tree_map/mod.rs
Closes #928 
Update the `TreeMap->Range` logic to keep track of current path. See the Issue description for detailed explanation.
=> perf (`TreeMap.range`): Update the TreeMap->Range logic

near-sdk/src/store/tree_map/iter.rs, near-sdk/src/store/tree_map/mod.rs
=> refactor: abstract common functions in `Keys` and `KeysRange`

near-sdk/src/utils/cache_entry.rs, near-sdk/src/utils/stable_map.rs
It also removes some unused types. I can't remember why those were kept in if it was a prediction of what would be needed, but they shouldn't be needed.
=> Add documentation to collection cache types

near-sdk-macros/Cargo.toml, near-sdk-macros/build.rs, near-sdk-macros/src/core_impl/abi/abi_embed.rs, near-sdk-macros/src/core_impl/abi/mod.rs, near-sdk-macros/src/core_impl/mod.rs, near-sdk-macros/src/lib.rs
`--all-features` causes cargo to activate all features in the `Cargo.toml` file.
This patch introduces an intermediary flag. Unknown to cargo, but injected with a build script if;
- The `__abi-embed` feature flag is activated.
- The `CARGO_NEAR_ABI_PATH` env is defined.
This way, it's never implicitly activated. Resolving the compilation error in #970.
This also means, we gravitate from this compilation error:
.. to this compilation warning ..
=> fix: `__abi-embed` compilation error

near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/info_extractor/arg_info.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs, near-sdk-macros/src/core_impl/info_extractor/impl_item_method_info.rs, near-sdk-macros/src/core_impl/info_extractor/item_trait_info.rs, near-sdk-macros/src/core_impl/info_extractor/trait_item_method_info.rs, near-sdk-macros/src/core_impl/utils/mod.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/self_support.rs
Resolves: #972, #1000.
This patch replaces any `Self` references in method signatures with the concrete type of the `impl` block itself.
Example:
```rust
#[near_bindgen]
#[derive(Serialize, Deserialize)]
struct MyType {
data: u8,
}
#[near_bindgen]
impl MyType {
fn set_state(&mut self, new_state: Self) -> Self {
std::mem::replace(self, new_state)
}
}
```
the impl block is transformed into:
```rust
impl MyType {
fn set_state(&mut self, new_state: MyType) -> MyType {
std::mem::replace(self, new_state)
}
}
```
this transformation is maintained regardless of type complexity or nesting level.
Worth noting, this does not transform `Self` references in generic bounds. But they're going to be prohibited following https://github.com/near/near-sdk-rs/pull/980 anyway. So I left it out.
=> fix: concretize `Self` references in method signatures

near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/code_generator/ext.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs, near-sdk-macros/src/core_impl/info_extractor/impl_item_method_info.rs, near-sdk-macros/src/core_impl/info_extractor/item_impl_info.rs, near-sdk-macros/src/core_impl/info_extractor/trait_item_method_info.rs, near-sdk-macros/src/core_impl/utils/mod.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/generic_const_function.rs, near-sdk/compilation_tests/generic_const_function.stderr, near-sdk/compilation_tests/generic_function.rs, near-sdk/compilation_tests/generic_function.stderr
=> fix: prohibit NEAR function generics

near-sdk-macros/src/core_impl/info_extractor/arg_info.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs, near-sdk-macros/src/core_impl/utils/mod.rs, near-sdk/compilation_tests/bad_argument.stderr
Closes #974 
We are already stripping function params of their lifetimes, seems reasonable to also do this for the return type.
=> fix: strip return types of lifetimes

near-sdk/src/store/free_list/mod.rs
This visibility change doesn't affect anything, because it was not exposed from the crate. This change is purely cosmetic and is just pre-emptive to make sure it doesn't get accidentally exposed in the future.
This method was used, then iirc the drop implementation made this irrelevant because it was more optimal for the use case (iterating over deleted values). Clear could be removed and then just use `.drop(..)` in the fuzz test, but this method could be useful in the future, so I decided to leave in. Can remove if anyone thinks otherwise, though!
=> Update visibility of FreeList and method

near-contract-standards/src/non_fungible_token/core/core_impl.rs
According to the [comments](https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/core/resolver.rs#L29) and [`nft_token` implementation](https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L412:L415), I think 'Extension Not Exists' vs 'Extension Exist But Value Not Exists' is different. i.e. If a contract doesn't have Approval Extension,  when we get `approved_account_ids`, it should be `None`, but if a contract does have Approval Extension, then we get `approved_account_ids`, it should be at least empty map, NEVER be `None`.
=> fix: approved account ids

near-sdk/src/store/tree_map/mod.rs
The bug was within the `remove` method of the entry API, which removed the element but did not update the root based on what was returned from do_remove.
This was a weird side effect to have to uphold after calling do_remove, so this seems like the correct refactor rather than just updating the root within that function.
Closes #993
=> fix(store::TreeMap): remove of the entry API now correctly updates the tree root when changed

near-contract-standards/src/non_fungible_token/core/resolver.rs
According to [NEP171](https://github.com/near/NEPs/blob/master/neps/nep-0171.md), the last param of `nft_resolve_transfer ` is `approved_account_ids`, and the [macro implementation](https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/macros.rs#L47) is also `approved_account_ids`, but in trait definition, it named `approvals`, it will cause unexpected JSON serialization result when cross call `nft_resolve_transfer` because the trait use `#[ext_contract]` macro. Currently, approval ids can not be revoked when `nft_transfer_call` failed.
=> fix: rename param `approvals` to `approved_account_ids`

near-contract-standards/src/non_fungible_token/core/core_impl.rs
We should remove any approvals receiver already set.
=> fix: remove receiver approval

near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs
As reported in #926, currently an `#[init]` method that returns a `Result`, but misses a `#[handle_result]` annotation compiles successfully, but causes problems at runtime.
This PR fixes that, so writing
```rust
#[init]
pub fn new() -> Result<Self, &'static str> { }
```
Now fails to compile with the 
```
Serializing Result<T, E> has been deprecated. Consider marking your method with #[handle_result]...
```
message, but writing
```rust
#[init]
#[handle_result]
pub fn new() -> Result<Self, &'static str> { }
```
compiles successfully as before.
=> fix: add compiler error for using Result with init

near-sdk/src/store/free_list/mod.rs, near-sdk/src/store/mod.rs, near-sdk/src/store/tree_map/iter.rs, near-sdk/src/store/unordered_map/mod.rs, near-sdk/src/store/unordered_set/iter.rs, near-sdk/src/store/vec/mod.rs
Closes #990 
This PR picks up where #992 left off (thanks @askoa!). The implementation is mostly the same except:
- `FreeList::defrag` does not interact with `Vector` internals (see comments in #992)
- `Vector` gets the new `remove_tail` method to support the above in a slightly more efficient fashion
- the `defrag` test does not assert stuff irrelevant to the feature - those assertions are instead pulled into new, more atomic tests (`new_bucket_is_empty`, `occupied_count_gets_updated`)
=> Freelist defrag

near-sdk-macros/src/core_impl/info_extractor/arg_info.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs, near-sdk-macros/src/core_impl/utils/mod.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/cond_compilation.rs, near-sdk/compilation_tests/self_forbidden_in_non_init_fn_arg.rs, near-sdk/compilation_tests/self_forbidden_in_non_init_fn_return.rs, near-sdk/compilation_tests/self_support.rs
This is part of #1005, but doesn't close the issue.
I really wanted to produce nice compiler warnings with spans using the Proper Way, but [the API is unstable](https://doc.rust-lang.org/proc_macro/struct.Diagnostic.html). I've turned to the dark side and am using `println` instead. Happy for ideas on how to improve this!
The code already collects spans of all forbidden `Self` tokens. Once we switch to prohibiting this completely, it should be easy to emit compile errors using these spans with a much better DX.
=> Deprecate `Self` in non-init function's return type

near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/code_generator/attr_sig_info.rs, near-sdk-macros/src/core_impl/code_generator/ext.rs, near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/code_generator/serializer.rs, near-sdk-macros/src/core_impl/info_extractor/arg_info.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs, near-sdk-macros/src/core_impl/info_extractor/impl_item_method_info.rs, near-sdk-macros/src/core_impl/info_extractor/mod.rs, near-sdk-macros/src/core_impl/info_extractor/trait_item_method_info.rs
This PR continues where #1033 left off. 
The PR first adds test coverage for the abi generator in 338c0b1a5f607c2681f2306ba274acf916e0b9b4 (fixes #1031). The tests don't cover all combinations, but they should cover all features.
In the second step, the PR refactors the abi generator to use the new `AttrSigInfo` struct introduced in #1025 (fixes #1032).
Finally, the PR cleans up the code that was necessary to support two versions of the `AttrSigInfo` struct while the refactoring was in progress.
=> refactor: use attr sig info in abi generator

.github/workflows/test.yml, CONTRIBUTING.md, near-sdk-macros/src/core_impl/abi/abi_generator.rs, run-tests.sh
This PR changes the flags to `clippy` in the CI to cover all features. Previously the abi generator code in bindgen wasn't covered.
There are two related commits in this branch:
470c3769834f44a9d20ee0b2d8eb13c70aaecf12 to fix the error discovered by expanding `clippy` coverage.
a077e8cfb4162c8d48bd1781abe2722631de4501 to provide a single script to run all checks locally that are ran by the CI.
=> ci: cover all features with clippy

near-sdk-macros/src/core_impl/info_extractor/visitor.rs
As discussed in #1040, we jumped the gun on disallowing private init methods. In 4.x they should be deprecated and only disallowed in 5.0.
This PR rolls back emitting a compilation error for private init methods and instead just logs a warning. 
We cannot use the `#[deprecated]` attribute, since the `#[private]` attribute itself is not deprecated. 
Using the [`Diagnostic`](https://doc.rust-lang.org/proc_macro/struct.Diagnostic.html#method.warning) would be more elegant than a `println`, but unfortunately it's unstable at this time.
=> refactor: change private init method from error to warning

near-sdk-macros/src/core_impl/abi/abi_embed.rs, near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/code_generator/attr_sig_info.rs, near-sdk-macros/src/core_impl/code_generator/ext.rs, near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs, near-sdk-macros/src/core_impl/code_generator/item_trait_info.rs, near-sdk-macros/src/core_impl/code_generator/serializer.rs, near-sdk-macros/src/core_impl/event/mod.rs, near-sdk-macros/src/core_impl/metadata/metadata_generator.rs, near-sdk-macros/src/core_impl/metadata/metadata_visitor.rs, near-sdk-macros/src/lib.rs
Closes #1058 
Switching to global paths (the ones that start with `::`) means the intended symbols can't be shadowed by user code except maybe by more advanced things like aliasing crates via `extern`.
=> Use global paths in macro expansions

near-sdk/src/environment/env.rs, near-sdk/src/types/vm_types.rs
Closes #945
This is **breaking** and should only be released with a major version bump (5.0.0)
=> Make `PromiseIndex` a newtype

.github/workflows/test.yml
It would be nice to create an `audit.toml` going forward and have comments there in regards to what and why is ignored.
=> [Fix] Ignore a security audit error.

.cargo/audit.toml, .github/workflows/test.yml
Closes https://github.com/near/near-sdk-rs/issues/1071
Using an config file for audit reports and comments.
=> chore: adding an `audit.toml` file

CHANGELOG.md, Cargo.toml, contract-builder/build.sh, examples/adder/Cargo.toml, examples/adder/src/lib.rs, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.toml, examples/factory-contract/tests/workspaces.rs, examples/fungible-token/Cargo.toml, examples/fungible-token/test-contract-defi/Cargo.toml, examples/lockable-fungible-token/Cargo.toml, examples/mission-control/Cargo.toml, examples/non-fungible-token/Cargo.toml, examples/status-message/Cargo.toml, examples/test-contract/Cargo.toml, examples/versioned/Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml, near-sys/CHANGELOG.md, near-sys/Cargo.toml
* `near-sdk`: 4.1.1 -> 5.0.0 (⚠️ API breaking changes)
* `near-sdk-macros`: 4.1.1 -> 5.0.0
* `near-sys`: 0.2.0 -> 0.2.1 (✓ API compatible changes)
* `near-contract-standards`: 4.1.1 -> 5.0.0 (✓ API compatible changes)
```
--- failure enum_variant_missing: pub enum variant removed or renamed ---
Description:
A publicly-visible enum has at least one variant that is no longer available under its prior name. It may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.24.2/src/lints/enum_variant_missing.ron
Failed in:
variant PromiseError::NotReady, previously in file /tmp/.tmpGbdLOj/near-sdk/src/types/vm_types.rs:41
variant PromiseResult::NotReady, previously in file …
```
=> chore: release v5.0.0-alpha.1

.github/workflows/test.yml, near-sdk-macros/src/core_impl/abi/abi_generator.rs
this prevents compiling sample contract
```rust
use near_sdk::borsh::{BorshDeserialize, BorshSerialize};
use near_sdk::near_bindgen;
#[near_bindgen]
#[derive(Default, BorshDeserialize, BorshSerialize)]
#[borsh(crate = "near_sdk::borsh")]
pub struct Contract {}
#[near_bindgen]
impl Contract {
pub fn foo(&self, a: bool, b: u32) {}
}
```
with `cargo build --features "near-sdk/__abi-generate"`
=> fix: remove leftover `near_sdk::__private::schemars`

.github/workflows/test.yml, near-sdk-macros/src/core_impl/code_generator/metadata.rs, near-sdk-macros/src/core_impl/code_generator/mod.rs, near-sdk-macros/src/lib.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/contract_metadata_bindgen.rs, near-sdk/compilation_tests/impl_generic.rs, near-sdk/compilation_tests/impl_generic.stderr
Fixes https://github.com/near/near-sdk-rs/issues/1117
=> [Fix] Contract source metadata compilation issue.

near-sdk/src/private/mod.rs
this prevents compiling sample contract with `cargo build --features "near-sdk/__abi-generate"`
```rust
use near_sdk::borsh::{BorshDeserialize, BorshSerialize};
use near_sdk::near_bindgen;
#[near_bindgen]
#[derive(Default, BorshDeserialize, BorshSerialize)]
#[borsh(crate = "near_sdk::borsh")]
pub struct Contract {}
#[near_bindgen]
impl Contract {
#[handle_result]
pub fn foo(&self) -> Result<u32, &'static str> {
Ok(1)
}
}
```
=> fix: include `near-sdk/src/private/result_type_ext.rs` file into module tree

near-contract-standards/src/fungible_token/mod.rs, near-contract-standards/src/non_fungible_token/approval/mod.rs, near-contract-standards/src/non_fungible_token/mod.rs, near-sdk-macros/src/core_impl/code_generator/attr_sig_info.rs, near-sdk-macros/src/core_impl/code_generator/mod.rs, near-sdk/src/types/public_key.rs
[similar issue](https://github.com/rust-lang/rust/issues/117120)
=> ci: fix new 1.75 warnings

README.md
this may help in cases like #1129
=> doc: add `#[borsh(crate =...)]` mentions in readme (#1129)

CHANGELOG.md, Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk`: 5.0.0-alpha.1 -> 5.0.0-alpha.2 (⚠️ API breaking changes)
* `near-sdk-macros`: 5.0.0-alpha.1 -> 5.0.0-alpha.2
* `near-contract-standards`: 5.0.0-alpha.1 -> 5.0.0-alpha.2 (✓ API compatible changes)
```
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.27.0/src/lints/enum_missing.ron
Failed in:
enum near_sdk::mock::VmAction, previously in file /tmp/.tmpV1uU7t/near-sdk/src/environment/mock/receipt.rs:12
``` …
=> chore: release

.github/workflows/test.yml, near-contract-standards/src/fungible_token/metadata.rs, near-contract-standards/src/non_fungible_token/metadata.rs, near-contract-standards/src/non_fungible_token/token.rs, near-sdk-macros/src/lib.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/types.rs, near-sdk/src/collections/legacy_tree_map.rs, near-sdk/src/collections/lookup_map.rs, near-sdk/src/collections/lookup_set.rs, near-sdk/src/collections/tree_map.rs, near-sdk/src/collections/unordered_map/mod.rs, near-sdk/src/collections/unordered_set.rs, near-sdk/src/collections/vector.rs, near-sdk/src/json_types/hash.rs, near-sdk/src/json_types/integers.rs, near-sdk/src/json_types/vector.rs, near-sdk/src/lib.rs, near-sdk/src/store/free_list/mod.rs, near-sdk/src/store/index_map.rs, near-sdk/src/store/lazy/mod.rs, near-sdk/src/store/lazy_option/mod.rs, near-sdk/src/store/lookup_map/mod.rs, near-sdk/src/store/lookup_set/mod.rs, near-sdk/src/store/tree_map/iter.rs, near-sdk/src/store/tree_map/mod.rs, near-sdk/src/store/unordered_map/mod.rs, near-sdk/src/store/vec/mod.rs, near-sdk/src/types/public_key.rs
Adds ability to set borsh attributes as `#[near(serializers=[borsh(use_discriminant=false), json])`
Adds near macro which contain borsh/json schema for all the types
=> Add Borsh/Json -Schema to types

near-sdk/src/store/iterable_map/entry.rs, near-sdk/src/store/iterable_map/impls.rs, near-sdk/src/store/iterable_map/iter.rs, near-sdk/src/store/iterable_map/mod.rs, near-sdk/src/store/mod.rs, near-sdk/src/store/vec/iter.rs
Fixes https://github.com/near/near-sdk-rs/issues/1134
To test this version of SDK, change your Cargo.toml like this:
```diff
-near-sdk = "5.1.0"
+near-sdk = { git = "https://github.com/ruseinov/near-sdk-rs", branch = "ru/feature/iterable-map" }
```
=> [Feature] IterableMap implementation.

near-sdk/src/store/index_map.rs, near-sdk/src/store/lookup_map/mod.rs, near-sdk/src/store/vec/mod.rs, near-sdk/src/utils/stable_map.rs
Make sure the new `store::IterableMap` that has been recently introduced is secure and bug-free by covering the collections it relies upon with tests.
=> [Enhancement] Cover 'store' collections with tests.

examples/fungible-token/test-contract-defi/src/lib.rs, near-sdk-macros/src/core_impl/info_extractor/attr_sig_info.rs, near-sdk/compilation_tests/schema_derive_invalids.stderr, near-sdk/src/lib.rs
this new lint was silenced , it introduces 30+ locations to fix:  https://rust-lang.github.io/rust-clippy/master/index.html#/multiple_bound_locations ; it has no automatic fix yet with `cargo clippy --fix`
=> ci: fix new lints, introduced in 1.78

near-sdk/src/environment/env.rs, near-sys/src/lib.rs
Yield Execution will be stabilized in nearcore in the 1.40 release.
This PR adds imports for the `promise_yield_create` and `promise_yield_resume` host functions. They have been tested using the smart contract example in #1133.
In the future we can also merge a cleaned-up version of the example contract.
Not sure what's going on with the failing tests; it seems like master is red too if I run them locally?
=> add yield execution host functions

near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/code_generator/ext.rs, near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs, near-sdk-macros/src/core_impl/code_generator/snapshots/arg_mut_ref.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/arg_no_return_no_mut.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/arg_ref.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/args_no_return_mut.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/args_return_mut.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/args_return_mut_borsh.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/args_return_ref.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/callback_args.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/callback_args_mixed_serialization.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/callback_args_only.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/callback_args_results.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/callback_args_vec.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/handle_result_borsh.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/handle_result_json.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/handle_result_mut.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/mut_owned_no_args_no_return.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/no_args_no_return_mut.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/no_args_no_return_mut_payable.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/no_args_no_return_no_mut.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/owned_no_args_no_return_no_mut.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/private_method.snap, near-sdk-macros/src/core_impl/code_generator/snapshots/trait_implt.snap, near-sdk-macros/src/core_impl/info_extractor/impl_item_method_info.rs, near-sdk-macros/src/core_impl/info_extractor/item_impl_info.rs, near-sdk/compilation_tests/schema_derive_invalids.stderr
Hey Team!
I've noticed a small inconsistency while working on [`#[access_control]`](https://github.com/Near-One/near-plugins/blob/12d3feec8686a9200173d3c72dbf5159309ded13/near-plugins-derive/src/lib.rs#L54) from [near-plugins](https://github.com/Near-One/near-plugins), which [uses](https://github.com/Near-One/near-plugins/blob/12d3feec8686a9200173d3c72dbf5159309ded13/near-plugins-derive/src/access_controllable.rs#L587-L588) `#[near-sdk::near]` macro internally.
The inconsistency itself can be described as follows:
> The generated code by `#[near_bindgen]`  assumes that all necessary traits were imported into current scope.
To simplify the issue, consider the following example:
```rust
use near_sdk::near;
pub mod other {
pub trait SomeTrait {
fn method(&self);
}
}
#[near(contract_state)] …
```
=> fix(macro): use FQDNs when calling contract methods

README.md, examples/fungible-token/README.md, examples/non-fungible-token/README.md
- Replaced a relative link to `CONTRIBUTING.md` with an absolute link to this file on github, to make this link work on https://crates.io/crates/near-sdk. It didn't work because crates.io uses README from `/near-sdk/README.md`, which is a symlink to `/README.md`. I replaced it with an absolute link because I'm not sure if it's possible to get relative links to work in both `/README.md` and `near-sdk/README.md` without maintaining 2 copies of the same file.
- Replaced `FungibleTokenCore` (moved to `FungibleToken/Core`) nomicon link with `FungibleToken`. The example implements all Fungible Token standards, so no reason to link to `FungibleToken/Core`, and now it's consistent with the Non-Fungible Token example.
- Replaced `NonFungibleToken/README.html` link with `NonFungibleToken`, and …
=> docs: Fix dead links in markdown files

near-sdk/src/utils/mod.rs
This PR makes `log!` macro 100% compatible with std `format!`, allowing string interpolation while passing just 1 string literal.
I also noticed that this macro uses `format` from local scope, now it's prefixed with `::std` to make sure it can't be accidentally overridden.
Fixes: #1188 
**BREAKING CHANGE**: `let x = "1"; log!(x)` doesn't work anymore, and `log!("str with no formatting")` now allocates, like `format!`. For logging `&str` with no additional formatting and no allocations, use `env::log_str` method instead.
=> fix: Make log macro fully compatible with std::format

.github/workflows/test.yml, near-sdk-macros/src/core_impl/info_extractor/arg_info.rs, near-sdk-macros/src/core_impl/info_extractor/trait_item_method_info.rs, near-sdk/Cargo.toml, near-sdk/compilation_tests/schema_derive_invalids.stderr, near-sdk/src/environment/env.rs, near-sdk/src/json_types/integers.rs, near-sdk/src/store/iterable_map/mod.rs, near-sdk/src/store/lookup_map/mod.rs
this passes if `macos-latest` is temporarily commented out https://github.com/near/near-sdk-rs/actions/runs/9566693799 ;
otherwise, `macos-latest` is having some serious trouble on 1.79
=> ci: 1.79 fixes (replace `macos-latest stable` with `macos-latest 1.78`)

near-contract-standards/src/non_fungible_token/approval/mod.rs, near-contract-standards/src/non_fungible_token/core/mod.rs, near-contract-standards/src/non_fungible_token/enumeration/mod.rs, near-contract-standards/src/non_fungible_token/metadata.rs
This PR exports `ext_nft_*` modules, so NFT interfaces can be re-used in dependent contracts
=> feat(near-contract-standards): export ext_nft_*

near-contract-standards/src/storage_management/mod.rs
The PR exports the `ext_storage_management`, which allows the creation of promises based on the `StorageManagement` trait.
=> feat(near-contract-standards): export ext_storage_management

.github/workflows/test.yml, near-sdk-macros/src/lib.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/lifetime_method_result.rs, near-sdk/src/store/unordered_map/mod.rs
checked against [test_unord_map_contract](https://github.com/dj8yfo/test_unord_map_contract/tree/master)
```bash
• Building contract
│    Compiling test_contract v0.1.0 (/home/user/Documents/code/test_contract)
│ warning: unused import: `log`
│  --> src/lib.rs:1:16
│   |
│ 1 | use near_sdk::{log, near};
│   |                ^^^
│   |
│   = note: `#[warn(unused_imports)]` on by default
│
│ warning: use of deprecated struct `near_sdk::store::UnorderedMap`: Suboptimal iteration performance. See performance considerations doc for details.
│  --> src/lib.rs:5:33
│   |
│ 5 |     greetings: near_sdk::store::UnorderedMap<String, String>,
│   |                                 ^^^^^^^^^^^^
│   |
│   = note: `#[warn(deprecated)]` on by default
│
│ warning: use of deprecated struct …
```
=> chore: add implicit `BorshSchema` derive for `store::UnorderedMap`

near-sdk/Cargo.toml, near-sdk/compilation_tests/schema_derive.rs, near-sdk/src/store/free_list/mod.rs, near-sdk/src/store/free_list/snapshots/near_sdk__store__free_list__tests__borsh_schema.snap, near-sdk/src/store/iterable_map/mod.rs, near-sdk/src/store/iterable_map/snapshots/near_sdk__store__iterable_map__test_map__borsh_schema.snap, near-sdk/src/store/iterable_set/mod.rs, near-sdk/src/store/iterable_set/snapshots/near_sdk__store__iterable_set__tests__borsh_schema.snap, near-sdk/src/store/unordered_map/mod.rs, near-sdk/src/store/unordered_map/snapshots/near_sdk__store__unordered_map__tests__borsh_schema.snap, near-sdk/src/store/vec/mod.rs, near-sdk/src/store/vec/snapshots/near_sdk__store__vec__tests__borsh_schema.snap
<details>
<summary>for `near_sdk::store::free_list::FreeList<T>`</summary><p>
from 
```rust
impl<T> crate::borsh::BorshSchema for FreeList<T>
impl<T> crate::borsh::BorshSchema for FreeList__NEAR_SCHEMA_PROXY<T>
impl<T> borsh::ser::BorshSerialize for FreeList<T>
impl<T> borsh::de::BorshDeserialize for FreeList<T>
```
to
```rust
impl<T> crate::borsh::ser::BorshSerialize for FreeList<T>
impl<T> crate::borsh::de::BorshDeserialize for FreeList<T>
impl<T> crate::borsh::BorshSchema for FreeList<T>
```
</p></details>
<details>
<summary>for `near_sdk::store::vec::Vector<T>`</summary><p>
from
```rust
impl<T> crate::borsh::BorshSchema for Vector<T>
impl<T> crate::borsh::BorshSchema for Vector__NEAR_SCHEMA_PROXY<T>
impl<T> borsh::ser::BorshSerialize for Vector<T>
impl<T> borsh::de::BorshDeserialize …
```
=> chore: replace `NearSchema` with `near(inside_near_sdk)`; add missing `BorshSchema` p2

CHANGELOG.md, Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml, near-sdk/tests/test-contracts/store/src/lib.rs, near-sys/CHANGELOG.md, near-sys/Cargo.toml
* `near-sdk`: 5.1.0 -> 5.2.0
* `near-sdk-macros`: 5.1.0 -> 5.2.0
* `near-sys`: 0.2.1 -> 0.2.2
* `near-contract-standards`: 5.1.0 -> 5.2.0
<blockquote>
- Added `BorshSchema` impl for `store::TreeMap<K, V, H>` and `UnorderedSet<T, H>` ([#1213](https://github.com/near/near-sdk-rs/pull/1213))
- Added missing `BorshSchema` for IterableSet and IterableMap and refactored and added ABI defiintions tests ([#1212](https://github.com/near/near-sdk-rs/pull/1212))
- Added `BorshSchema` derive for `store::UnorderedMap` ([#1209](https://github.com/near/near-sdk-rs/pull/1209))
- New `near_sdk::store::IterableSet` - a better alternative to `UnorderedSet`, which has performance limitations on iteration over elements …
=> chore: release v5.2.0

near-sdk-macros/src/core_impl/contract_metadata/mod.rs
To avoid problems on older `<0.7.0` `cargo-near` versions
checked on  `cargo-near-near 0.6.2` 
before
```bash
near contract inspect before-cargo-pkg-fix.testnet network-config testnet now  
```
and after 
```bash
near contract inspect after-cargo-pkg-fix.testnet network-config testnet now
```
checked on potential `cargo-near-near 0.7.0` from [branch](https://github.com/near/cargo-near/tree/source-scan-integration)
after
(docker)
```bash
near contract inspect sample-crate-14.testnet network-config testnet now
```
--no-docker
```bash
near contract inspect sample-crate-15.testnet network-config testnet now
```
=> fix(nep330): return fallback vals of `CARGO_PKG_REPOSITORY` and `CARGO_PKG_VERSION`

examples/fungible-token/tests/workspaces.rs, near-sdk/src/store/mod.rs, near-sdk/src/test_utils/mod.rs
- This PR fix issue [#1223](https://github.com/near/near-sdk-rs/issues/1223)from [near-sdk ]( https://github.com/near/near-sdk-rs/)
- Need to address the following issues:
- Fixed broken test: Updated the upper limit of the assertions to be more flexible, allowing for small variations in gas rewards and contract balance. 
- Fixed comments indentation
=> 1223: Fix compilation errors

near-contract-standards/src/non_fungible_token/utils.rs, near-sdk/Cargo.toml
- This PR fix issue [#1160 ](https://github.com/near/near-sdk-rs/issues/1160)from [near-sdk ]( https://github.com/near/near-sdk-rs/)
- Need to add the `exact_amount_display` method to format `yoctoNEAR` values for clearer error message 
- This requires the [Near-token pull request](https://github.com/near/near-token-rs/pull/9) to be merged first.
- Added `exact_amount_display`  to format `NearToken` values
=> 1160: Fix storage management error message with proper amount

examples/adder/Cargo.toml, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/cross-contract-calls/high-level/Cargo.toml, examples/cross-contract-calls/low-level/Cargo.toml, examples/factory-contract/Cargo.toml, examples/factory-contract/high-level/Cargo.toml, examples/factory-contract/low-level/Cargo.toml, examples/fungible-token/ft/Cargo.toml, examples/fungible-token/test-contract-defi/Cargo.toml, examples/non-fungible-token/nft/Cargo.toml, examples/non-fungible-token/test-approval-receiver/Cargo.toml, examples/non-fungible-token/test-token-receiver/Cargo.toml, examples/test-contract/Cargo.toml, examples/versioned/Cargo.toml
- Resolves #1168 
- Adds `unit-testing` feature as dev dependencies in examples.
- verifies the working through error recreation method stated at https://github.com/near/near-sdk-rs/issues/1168#issuecomment-2151943980
=> unit testing feature init

.github/workflows/test.yml
=> ci:  test ci 1.80 with macos-latest

.github/workflows/test_examples.yml, .github/workflows/test_examples_small.yml, CONTRIBUTING.md, examples/factory-contract/tests/workspaces.rs, examples/non-fungible-token/Cargo.toml, examples/non-fungible-token/test-approval-receiver/src/lib.rs, examples/non-fungible-token/test-token-receiver/src/lib.rs, examples/versioned/Cargo.toml, examples/versioned/src/lib.rs, near-sdk/src/store/unordered_map/mod.rs, near-sdk/src/store/unordered_set/mod.rs
[Issue #1190](https://github.com/near/near-sdk-rs/issues/1190)
This PR addresses the following issues:
- Ensures examples `.wasm` files are built before running tests by updating CONTRIBUTING.md.
- Modifies CI workflow to build and test all examples in exception of factory-contracts.
- Adds missing unit-testing feature for `examples/non-fungible-token` and `examples/versioned`.
- Refactors deprecated features in examples.
- Updated CONTRIBUTING.md to include instructions for building examples.
- Modified `.github/workflows/test_examples_small.yml` and `.github/workflows/test_examples.yml` to build and test more examples.
- Added unit-testing feature for `examples/non-fungible-token` and `examples/versioned` in their Cargo.toml.
- Replaced deprecated `UnorderedMap` with `LookupMap` in …
=> Fix CI workflow and examples tests

near-sdk/src/store/lazy/mod.rs
Fixes https://github.com/near/near-sdk-rs/issues/1218
=> feat: introduce 'remove' method for 'near_sdk::store::Lazy' collection

examples/adder/Cargo.toml, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.toml, examples/fungible-token/Cargo.toml, examples/lockable-fungible-token/Cargo.toml, examples/non-fungible-token/Cargo.toml, near-sdk/Cargo.toml, near-sdk/tests/store_performance_tests.rs
near-workspaces should be updated later. It's not a blocker as it's used in tests and it has cyclic dependency :)
cc @race-of-sloths
=> chore: updates near-* dependencies to 0.24.0

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk`: 5.3.0 -> 5.4.0
* `near-sdk-macros`: 5.3.0 -> 5.4.0
* `near-contract-standards`: 5.3.0 -> 5.4.0
<blockquote>
- updates near-* dependencies to 0.25.0 ([#1242](https://github.com/near/near-sdk-rs/pull/1242))
- updates near-workspaces-rs ([#1239](https://github.com/near/near-sdk-rs/pull/1239))
</blockquote>
<blockquote>
- Fix storage management error message with proper amount ([#1222](https://github.com/near/near-sdk-rs/pull/1222))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v5.4.0

examples/adder/Cargo.toml, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.toml, examples/fungible-token/Cargo.toml, examples/lockable-fungible-token/Cargo.toml, examples/non-fungible-token/Cargo.toml, near-contract-standards/src/non_fungible_token/core/core_impl.rs, near-sdk/Cargo.toml, near-sdk/src/environment/mock/mocked_blockchain.rs, near-sdk/tests/store_performance_tests.rs, near-sdk/tests/test-contracts/store/Cargo.toml
The 1.81 release finishes the C-unwind transition: [Details](https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html#abort-on-uncaught-panics-in-extern-c-functions)
It's a bit weird that UnorderedMap performs better on 1.81 than UnorderedSet. UnorderedMap uses 100 T whereas UnorderedSet uses 106T on fewer iterations.
=> chore: updates near-* dependendencies. Migrates testing blockchain mock to C-unwind

CHANGELOG.md, Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk`: 5.4.0 -> 5.5.0
* `near-sdk-macros`: 5.4.0 -> 5.5.0
* `near-contract-standards`: 5.4.0 -> 5.5.0
<blockquote>
- Updated near-* dependendencies to v0.26.0. Migrated testing blockchain mock to C-unwind ([#1244](https://github.com/near/near-sdk-rs/pull/1244))
</blockquote>
<blockquote>
- Updated near-* dependendencies to v0.26.0. Migrated testing blockchain mock to C-unwind ([#1244](https://github.com/near/near-sdk-rs/pull/1244))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v5.5.0

near-sdk/src/store/mod.rs
Adding info about GAS consumption comparison between native and near collections.
=> Benchmarking of near collections

.github/workflows/test.yml, .github/workflows/test_examples.yml, .github/workflows/test_examples_small.yml, near-sdk/Cargo.toml, near-sdk/src/environment/env.rs, near-sdk/tests/store_performance_tests.rs
https://github.com/near/near-sdk-rs/blob/master/.github/workflows/test.yml#L19-L23 is not affected, because `Test Core` job uses [`near_workspaces::compile_project`](https://github.com/near/near-sdk-rs/blob/master/near-sdk/tests/store_performance_tests.rs#L58)
=> ci: freeze 1.81 for near-workspaces paths (temporarily)

.github/workflows/test.yml, README.md, near-sdk/Cargo.toml, near-sdk/src/environment/mock/mocked_blockchain.rs
=> chore: updates near-* dependencies to 0.27 release

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk`: 5.5.0 -> 5.6.0 (✓ API compatible changes)
* `near-sdk-macros`: 5.5.0 -> 5.6.0
* `near-contract-standards`: 5.5.0 -> 5.6.0
<blockquote>
- updates near-* dependencies to 0.27 release ([#1254](https://github.com/near/near-sdk-rs/pull/1254))
- freeze 1.81 for near-workspaces paths (temporarily) ([#1250](https://github.com/near/near-sdk-rs/pull/1250))
- Benchmark near collections and provide the results as the reference in the docs ([#1248](https://github.com/near/near-sdk-rs/pull/1248))
- Updated near-workspaces to 0.14 version (matching 0.26 near-* release) ([#1246](https://github.com/near/near-sdk-rs/pull/1246))
</blockquote>
<blockquote>
- Updated near-* dependendencies to v0.26.0. Migrated testing blockchain mock to …
=> chore: release v5.6.0

near-sdk/src/environment/env.rs
Make it straightforward for developers how host functions can be imported and used
The final markdown doc page will appear as follows
=> doc: examples for Near-related host functions

near-contract-standards/src/lib.rs, near-sdk/src/lib.rs
after comparing with #1266 the replacement `'_` doesn't look all that informative
mentioning https://github.com/rust-lang/rust-clippy/issues/13514
=> ci: allow clippy::needless_lifetimes (1.83 more suggestions)

.github/workflows/coverage.yml, .github/workflows/release-plz.yml, .github/workflows/test.yml, .github/workflows/test_examples.yml, .github/workflows/test_examples_small.yml, .github/workflows/typo.yml, near-contract-standards/src/fungible_token/mod.rs, near-contract-standards/src/lib.rs, near-sdk/src/store/mod.rs, near-sdk/src/test_utils/context.rs, near-sdk/src/test_utils/mod.rs, near-sdk/src/test_utils/test_env.rs
resolves #1264 
failed job due to warnings raised looks like this https://github.com/near/near-sdk-rs/actions/runs/12121010891/job/33791012532
=> ci: add a `cargo doc` job

near-sdk/src/store/mod.rs, near-sdk/tests/store_performance_tests.rs, near-sdk/tests/test-contracts/lazy/Cargo.toml, near-sdk/tests/test-contracts/lazy/src/lib.rs
work on https://github.com/near/near-sdk-rs/issues/1199
=> chore: tests for Lazy and moving out of unstable

.github/workflows/test.yml, near-sdk/Cargo.toml
Bumped up rust to the 1.82  
@race-of-sloths
=> chore: updates near-* dependencies to 0.28 release

near-sdk/src/types/public_key.rs
resolves #1280 
checked on such a contract
```rust
use near_sdk::PublicKey;
#[near(serializers = [json, borsh])]
pub struct Errors {
field: Vec<PublicKey>,
}
```
=> fix: impaired PublicKey having his BorshSchema missing

.github/workflows/test.yml, near-contract-standards/Cargo.toml, near-sdk-macros/Cargo.toml, near-sdk/Cargo.toml
this changes how `Trait implementations` section for  https://docs.rs/near-sdk/5.7.0/near_sdk/struct.PublicKey.html looks :
from 
to
=> doc: `__abi-generate` feature in docs.rs

CHANGELOG.md, Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk`: 5.7.0 -> 5.7.1 (✓ API compatible changes)
* `near-sdk-macros`: 5.7.0 -> 5.7.1
* `near-contract-standards`: 5.7.0 -> 5.7.1 (✓ API compatible changes)
<blockquote>
- improved documentation for near-sdk and near-sdk-macros crates (#1262)
- clippy lint of 1.84 fixed (#1290)
- `__abi-generate` feature in docs.rs (#1286)
- updates near-workspaces to 0.16 version (#1284)
- impaired PublicKey with missing BorshSchema (#1281)
</blockquote>
<blockquote>
- `__abi-generate` feature in docs.rs (#1286)
</blockquote>
</p></details>
---
=> chore: release v5.7.1

.github/codecov.yml
theoretically this should make coverage workflow not fail if single pr/change introduces less than 0.2% decrease of coverage
=> ci(.github): add codecov.yml for failure threshold

near-contract-standards/src/contract_metadata.rs
resolves #1292 
this comes together with https://github.com/near/near-api-rs/pull/46
=> chore(near-contract-standards): add `build_info` field

README.md, near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk-macros/src/core_impl/code_generator/attr_sig_info.rs, near-sdk-macros/src/lib.rs, near-sdk/src/json_types/vector.rs, near-sdk/src/lib.rs
Resolves: #1288
* Replaced `ignore` -> `rust` for examples to be able to test them in CI
=> doc: moved near-sdk-macros doc to near-sdk crate.

near-sdk-macros/src/lib.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/double_contract_state_error.rs, near-sdk/compilation_tests/double_contract_state_error.stderr, near-sdk/compilation_tests/nested_near_error.rs, near-sdk/compilation_tests/nested_near_error.stderr
This PR intends to clarify errors for the user. This PR doesn't introduce new errors, but rather clarifies them. As older compilation errors are hard to understand
* Added a new error message if the `near(contract_state)` was used two times in the same crate.
* Added a new error message if there is a nested `near` macro
**Contract state repetion**:
```
error: symbol `__near_abi_contract_source_metadata` is already defined
--> compilation_tests/double_contract_state_error.rs:9:5
|
9 |     #[near(contract_state)]
```
**`Near` macro nesting**:
```
error: multiple `borsh` attributes not allowed
--> compilation_tests/nested_near_error.rs:6:1
|
6  | / #[near(contract_metadata(
7  | |     version = "39f2d2646f2f60e18ab53337501370dc02a5661c",
8  | |     link = …
```
=> feat: improved error reporting for `near` macro

CHANGELOG.md, Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk`: 5.8.0
* `near-sdk-macros`: 5.8.0
* `near-contract-standards`: 5.8.0
<blockquote>
- *(near_sdk_macros)* improved error reporting for `near` macro (#1301)
- moved annotations to the near macro documentation.  (#1299)
- moved near-sdk-macros doc to near-sdk crate. (#1295)
</blockquote>
<blockquote>
</blockquote>
</p></details>
---
=> chore: release v5.8.0

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk`: 5.8.0 -> 5.8.1 (✓ API compatible changes)
* `near-sdk-macros`: 5.8.0 -> 5.8.1
* `near-contract-standards`: 5.8.0 -> 5.8.1
<blockquote>
- remove `double_contract_state_error` diagnostic (#1310)
</blockquote>
<blockquote>
</blockquote>
</p></details>
---
=> chore: release v5.8.1

near-sdk-macros/src/lib.rs, near-sdk/compilation_tests/schema_derive_invalids.stderr, near-sdk/src/environment/env.rs, near-sdk/src/lib.rs, near-sdk/src/near_annotations.rs
Fixes #1303
Adds documentation for the `callback_unwrap` attribute under the `#[near]` macro docs, including:
- Description of functionality and usage
- Integration with `PromiseOrValue`
- Cross-contract factorial example 
- Rust doc annotations and references
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/near/near-sdk-rs/pull/1313?shareId=f728c9fe-ce24-497b-8bde-8092b6e4dd04).
=> docs: document `callback_unwrap` attribute

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk-macros`: 5.8.1 -> 5.8.2
* `near-sdk`: 5.8.1 -> 5.8.2 (✓ API compatible changes)
* `near-contract-standards`: 5.8.1 -> 5.8.2
<blockquote>
- impl details of `#[callback_unwrap]` ([#1321](https://github.com/near/near-sdk-rs/pull/1321))
- `#[near(contract_state)]` in-depth pass ([#1307](https://github.com/near/near-sdk-rs/pull/1307))
- document `callback_unwrap` attribute ([#1313](https://github.com/near/near-sdk-rs/pull/1313))
</blockquote>
<blockquote>
</blockquote>
</p></details>
---
=> chore: release v5.8.2

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk-macros`: 5.8.2 -> 5.9.0
* `near-sdk`: 5.8.2 -> 5.9.0
* `near-contract-standards`: 5.8.2 -> 5.9.0
<blockquote>
- updates near-* dependencies to 0.29 release ([#1325](https://github.com/near/near-sdk-rs/pull/1325))
</blockquote>
<blockquote>
</blockquote>
</p></details>
---
=> chore: release v5.9.0

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk-macros`: 5.9.0 -> 5.10.0
* `near-sdk`: 5.9.0 -> 5.10.0 (✓ API compatible changes)
* `near-contract-standards`: 5.9.0 -> 5.10.0
<blockquote>
- `deny_unknown_arguments` on-method attribute ([#1328](https://github.com/near/near-sdk-rs/pull/1328))
</blockquote>
<blockquote>
</blockquote>
</p></details>
---
=> chore: release v5.10.0

near-sdk/src/environment/mock/mocked_blockchain.rs
Without this change the tests for the contracts that use yield API fail with the following compilation errors:
```
ld: warning: object file (/projects/near/mpc/libs/chain-signatures/target/debug/deps/libsecp256k1_sys-98527547b5aca695.rlib[6](fce6141bfa9bf74c-precomputed_ecmult.o)) was built for newer 'macOS' version (15.2) than being linked (15.0)
ld: warning: object file (/projects/near/mpc/libs/chain-signatures/target/debug/deps/libsecp256k1_sys-98527547b5aca695.rlib[7](fce6141bfa9bf74c-secp256k1.o)) was built for newer 'macOS' version (15.2) than being linked (15.0)
Undefined symbols for architecture arm64:
"_promise_yield_create", referenced from:
near_sdk::environment::env::promise_yield_create::h6ab688e32bb03837 in libnear_sdk-6b877ec05e41e84e.rlib[7](near_sdk-6b877ec05e41e84e.near_s …
```
=> feat: Added promise_yield_create and promise_yield_resume APIs to the mocked test utils

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk-macros`: 5.10.0 -> 5.11.0
* `near-sdk`: 5.10.0 -> 5.11.0 (✓ API compatible changes)
* `near-contract-standards`: 5.10.0 -> 5.11.0
<blockquote>
- Added promise_yield_create and promise_yield_resume APIs to the mocked test utils ([#1333](https://github.com/near/near-sdk-rs/pull/1333))
</blockquote>
<blockquote>
</blockquote>
</p></details>
---
=> chore: release v5.11.0

CHANGELOG.md, Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk-macros`: 5.11.0 -> 5.12.0
* `near-sdk`: 5.11.0 -> 5.12.0 (✓ API compatible changes)
* `near-contract-standards`: 5.11.0 -> 5.12.0 (⚠ API breaking changes)
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.40.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field BuildInfo.output_wasm_path in /tmp/.tmpY5Au7r/near-sdk-rs/near-contract-standards/src/contract_metadata.rs:183
``` …
=> chore: release v5.12.0

near-contract-standards/src/contract_metadata.rs
resolves https://github.com/near/NEPs/pull/606/files/1c5678510ae37f52037f1497e27febd564525d54#r2045175915
=> chore(near-contract-standards): deserialize `ContractSourceMetadata::standards` field so, as if it were optional

near-sdk-macros/src/core_impl/contract_metadata/mod.rs, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/contract_metadata-no-version-no-link.rs
When macros like `#[near]` tokenize the user input of metadata to put it in `ContractMetadata`, the way it's implemented now leads to invalid meta if the user doesn't include version or link. This happens because, for example, a non-existing version is tokenized to `version = ` instead of nothing. This leads to compilation errors that originate at `MacroConfig::from_list(...)`, since a key without a valid value is not seen as valid meta code.
This PR fixes that issue for both `version` and `link`. Now both work correctly and can be omitted, and they will be inherited from cargo attributes.
=> Fix the tokenization of of ContractMetadata, where it can lead to invalid meta

near-sdk/src/environment/env.rs
0 is success, 1 is failure, 2 is error. 
https://github.com/near/nearcore/blob/a0269d8a73d932b70586f9837a01e0297b648c35/runtime/near-vm-runner/src/logic/bls12381.rs#L286
=> Fix BLS12-381 pairing check return value comparison

.github/workflows/coverage.yml, .github/workflows/test.yml, .github/workflows/test_examples.yml, .github/workflows/test_examples_small.yml, examples/adder/Cargo.toml, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.toml, examples/factory-contract/high-level/Cargo.toml, examples/factory-contract/high-level/build.rs, examples/factory-contract/low-level/Cargo.toml, examples/factory-contract/low-level/build.rs, examples/fungible-token/Cargo.toml, examples/fungible-token/tests/workspaces.rs, examples/lockable-fungible-token/Cargo.toml, examples/lockable-fungible-token/tests/workspaces.rs, examples/mission-control/Cargo.toml, examples/mpc-contract/Cargo.toml, examples/non-fungible-token/Cargo.toml, examples/non-fungible-token/tests/workspaces/utils.rs, examples/status-message/Cargo.toml, examples/test-contract/Cargo.toml, examples/versioned/Cargo.toml, near-sdk/Cargo.toml
this avoids compiling `wasm-opt` in ci and locally, and installing binary dependency in CI is quite fast : 
current `master`
```bash
❯ : cargo tree -i wasm-opt
wasm-opt v0.116.1
└── cargo-near-build v0.4.5
└── near-workspaces v0.18.0
[dev-dependencies]
└── near-sdk v5.12.0 (/home/jerrick/Documents/code/near/near-sdk-rs-worktrees/near-sdk-rs/near-sdk)
└── near-contract-standards v5.12.0 (/home/jerrick/Documents/code/near/near-sdk-rs-worktrees/near-sdk-rs/near-contract-standards)
[dev-dependencies]
├── near-contract-standards v5.12.0 (/home/jerrick/Documents/code/near/near-sdk-rs-worktrees/near-sdk-rs/near-contract-standards)
└── near-sdk v5.12.0 (/home/jerrick/Documents/code/near/near-sdk-rs-worktrees/near-sdk-rs/near-sdk) (*)
```
\+ examples
pr's target branch
```bash
❯ : cargo tree -i …
```
=> ci: update `near-workspaces`, `cargo-near-build`in examples and core tests  to avoid `wasm-opt` compile

.github/workflows/compare_sizes.yml
this has been somewhat skipped in #1350 ; 
this is  needed to live test/fine tune in ci modified `ci/compare_sizes/compare_sizes.py` in scope of #1343,
because `/compare` directives appear to trigger `.github/workflows/compare_sizes.yml` workflow from default branch, and not from commented-on issue/pr (there's no associated GITHUB_COMMIT for an issue at all https://github.com/near/near-sdk-rs/actions/runs/14844334355)
which is mentioned in comments https://github.com/near/near-sdk-rs/pull/1343#issuecomment-2824364811 and https://github.com/near/near-sdk-rs/pull/1343#issuecomment-2851363615
=> ci: add cargo-near install to compare_sizes.yml

CHANGELOG.md, Cargo.toml, near-contract-standards/CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml, near-sys/CHANGELOG.md, near-sys/Cargo.toml
* `near-sdk-macros`: 5.13.0 -> 5.14.0
* `near-sys`: 0.2.3 -> 0.2.4 (✓ API compatible changes)
* `near-sdk`: 5.13.0 -> 5.14.0 (✓ API compatible changes)
* `near-contract-standards`: 5.13.0 -> 5.14.0 (✓ API compatible changes)
<blockquote>
- updates near-* dependencies to 0.30 release ([#1356](https://github.com/near/near-sdk-rs/pull/1356))
</blockquote>
<blockquote>
- updates near-workspaces to 0.20 version ([#1358](https://github.com/near/near-sdk-rs/pull/1358))
- updates near-* dependencies to 0.30 release ([#1356](https://github.com/near/near-sdk-rs/pull/1356))
</blockquote>
<blockquote>
- updates near-* dependencies to 0.30 release ([#1356](https://github.com/near/near-sdk-rs/pull/1356))
</blockquote>
</p></details>
---
This PR was …
=> chore: release 5.14.0

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk-macros`: 5.14.0 -> 5.15.0
* `near-sdk`: 5.14.0 -> 5.15.0 (✓ API compatible changes)
* `near-contract-standards`: 5.14.0 -> 5.15.0
<blockquote>
- Added a new `.to_json()` method for Events in addition to `.emit()` ([#1360](https://github.com/near/near-sdk-rs/pull/1360))
- Hint developers to use `cargo near build` to build contracts instead of `cargo build` ([#1361](https://github.com/near/near-sdk-rs/pull/1361))
- Include detailed error information on deserialization errors for function input arguments to improve troubleshooting experience for devs ([#1363](https://github.com/near/near-sdk-rs/pull/1363))
- expand cfgs' compilation error with complete reason of the error …
=> chore: release v5.15.0

near-sdk/src/lib.rs, near-sdk/src/promise.rs
Send the same outgoing data dependency to many function calls that run after.
This has always been possible with the low-level API but the Promise API was not expressive enough.
Specifically, in `near_sys::promise_then`, one can use the same promise index more than once.
https://github.com/near/near-sdk-rs/blob/985c16b8fffc623096d0b7e60b26746842a2d712/near-sys/src/lib.rs#L77-L87
However, using the SDK's promise API, [`Promise::then`](https://docs.rs/near-sdk/latest/near_sdk/struct.Promise.html#method.then) consumes the promise, which makes calling `then` twice impossible.
This adds method `then_concurrent` to allow more complex dependencies. This method returns `ConcurrentPromises` that can be joined and chained again.
See the included doc comments and tests for examples.
=> feat: then_concurrent() for Promise API

CHANGELOG.md, Cargo.toml, near-contract-standards/Cargo.toml, near-sdk/Cargo.toml
* `near-sdk-macros`: 5.17.1 -> 5.17.2
* `near-sdk`: 5.17.1 -> 5.17.2 (✓ API compatible changes)
* `near-contract-standards`: 5.17.1 -> 5.17.2
<blockquote>
- Auto-document features on docs.rs + improved wording for the top-level documentation ([#1386](https://github.com/near/near-sdk-rs/pull/1386))
</blockquote>
<blockquote>
- updates near-* dependencies to 0.30 release ([#1356](https://github.com/near/near-sdk-rs/pull/1356))
</blockquote>
</p></details>
---
=> chore: release v5.17.2
