near-bindgen/src/environment/env.rs, near-bindgen/src/environment/mocked_blockchain.rs
Tests are concurrent for BLOCKCHAIN_INTERFACE. Moved BLOCKCHAIN_INTERFACE into thread_local variable to not share it b/w threads.
=> Fix tests race condition

Cargo.lock, near-bindgen/Cargo.toml, near-bindgen/compilation_tests/all.rs
=> Run compile tests on stable only

examples/cross-contract-high-level/build.sh, examples/cross-contract-low-level/build.sh, examples/fun-token/build.sh, examples/mission-control/build.sh, examples/status-message-collections/build.sh, examples/status-message/build.sh
This speeds up builds significantly
=> Keep target dir in build.sh of examples to improve developer experience

near-bindgen-macros/res/near_blockchain.rs, near-bindgen-macros/res/sys.rs, near-bindgen/src/environment/blockchain_interface.rs, near-bindgen/src/environment/env.rs, near-bindgen/src/environment/mocked_blockchain.rs
Related to: https://github.com/nearprotocol/nearcore/pull/2045
=> Add keccak256 and keccak512 native support

Cargo.lock, near-sdk-core/Cargo.toml
=> Reduce dependencies

near-sdk/src/collections/set.rs, near-sdk/src/collections/unordered_map.rs, near-sdk/src/collections/vector.rs
=> fix CI tests

CODEOWNERS
Update CODEOWNERS to remove @olonho and add @willemneal with @frol
=> Change CODEOWNERS

Cargo.lock, Cargo.toml, examples/cross-contract-low-level/Cargo.lock, examples/fungible-token/Cargo.lock, examples/fungible-token/tests/general.rs, examples/mission-control/Cargo.lock, near-sdk-sim/Cargo.toml, near-sdk-sim/src/outcome.rs, near-sdk-sim/src/runtime.rs
ExecutionResult now contains ProfileData.
=> fix: update toml and add profile data

near-sdk/src/environment/env.rs
Updating the storage byte cost, as soon as mainnet flips to it.
=> Storage byte cost was dropped

near-sdk/src/environment/env.rs
=> fix warnings

near-sdk/src/json_types/vector.rs
- Moves impls into a module so it can easily be used for annotating new structures which allows keeping fields the ideal type.
- I didn't export this module in any way as to not make a breaking change, but let me know if you want me to
- Updates intermediate type to `Cow` to avoid an allocation in some cases
=> refactor(json_types): abstract base64 serialization and improve deserialization

near-contract-standards/src/non_fungible_token/core/mod.rs
After some refactoring to the nft standard, some doc links whiffed.
=> fix(nft): refactored intra doc links

near-contract-standards/src/fungible_token/storage_impl.rs
=> typo: mimimum » minimum

near-sdk/src/environment/mock/receipt.rs
Esp since this is just used for testing, I noticed a contract I am migrating would benefit a lot from this.
=> feat: add Eq/PartialEq to Receipt and actions

near-sdk/Cargo.toml, near-sdk/src/store/vec/mod.rs
I'm in progress with refactoring the internals of this but figured I could PR this separately to make the transition cleaner
=> test(vector): Add fuzz test for Vector

CHANGELOG.md
=> chore: update changelog to note missed changes

CODEOWNERS
=> Remove Mike Purvis from codeowners ❤️

near-contract-standards/src/non_fungible_token/core/core_impl.rs, near-contract-standards/src/non_fungible_token/events.rs
I just did basically the minimum amount to fix, didn't look at all changes.
Also added #[non_exhaustive] to the enum variants so that adding new ones aren't a breaking change
@BenKurrek
=> make slight changes to fix events format

near-sdk-sim/src/runtime.rs, near-sdk/src/environment/mock/mocked_blockchain.rs, near-sdk/src/lib.rs
The new clippy version borks some things
=> fix(clippy): New warnings and annotation

near-sdk/src/store/mod.rs, near-sdk/src/store/unordered_map/mod.rs, near-sdk/src/store/unordered_set/impls.rs, near-sdk/src/store/unordered_set/iter.rs, near-sdk/src/store/unordered_set/mod.rs
=> feat(store): UnorderedSet v2 caching implementation

CHANGELOG.md, near-sdk/src/types/vm_types.rs
=> feat: Add Debug and PartialEq impls to PromiseError

CHANGELOG.md, near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs, near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs, near-sdk/src/types/error.rs, near-sdk/src/types/mod.rs
=> feat: cause compilation to fail when trying to serialize `Result` value

CHANGELOG.md
=> docs: fix changelog PR link

README.md
Made minor changes to the README.
=> docs: minor changes to readme

near-contract-standards/src/non_fungible_token/metadata.rs, near-contract-standards/src/non_fungible_token/token.rs, near-sdk/src/collections/tree_map.rs, near-sdk/src/json_types/vector.rs, near-sdk/src/private/abi.rs, near-sdk/src/store/tree_map/mod.rs, near-sdk/src/types/error.rs, near-sdk/src/types/mod.rs, near-sdk/src/types/vm_types.rs
New Rust/clippy version, new warnings (fixes CI)
=> feat: Add Eq to PartialEq derives and fix clippy

examples/abi/Cargo.lock, examples/abi/res/abi.json, examples/fungible-token/Cargo.lock, near-sdk/Cargo.toml
https://github.com/near/near-abi-rs/pull/3
=> chore: update near-abi

near-contract-standards/src/non_fungible_token/metadata.rs, near-contract-standards/src/non_fungible_token/token.rs
needed for building an ABI with the NFT example
=> feat: add JsonSchema derives to NFT exposed types

.github/workflows/test.yml, CHANGELOG.md, near-contract-standards/Cargo.toml, near-sdk-macros/src/core_impl/abi/abi_generator.rs, near-sdk/Cargo.toml, near-sdk/src/lib.rs
Context: https://github.com/near/near-sdk-rs/pull/939#issuecomment-1285987782
Linked with: https://github.com/near/cargo-near/pull/80
=> abi generator: return raw byte array instead of CString

CHANGELOG.md, examples/adder/Cargo.lock, examples/callback-results/Cargo.lock, examples/cross-contract-calls/Cargo.lock, examples/factory-contract/Cargo.lock, examples/fungible-token/Cargo.lock, examples/lockable-fungible-token/Cargo.lock, examples/mission-control/Cargo.lock, examples/non-fungible-token/Cargo.lock, examples/status-message-collections/Cargo.lock, examples/status-message/Cargo.lock, examples/test-contract/Cargo.lock, examples/versioned/Cargo.lock, near-contract-standards/Cargo.toml, near-sdk-macros/Cargo.toml, near-sdk/Cargo.toml
Still waiting on a few small things, just prepping this to get ready for the release
=> chore: prep 4.1.0 release

.github/workflows/test.yml, CHANGELOG.md, examples/adder/Cargo.lock, examples/callback-results/Cargo.lock, examples/cross-contract-calls/Cargo.lock, examples/factory-contract/Cargo.lock, examples/fungible-token/Cargo.lock, examples/lockable-fungible-token/Cargo.lock, examples/mission-control/Cargo.lock, examples/non-fungible-token/Cargo.lock, examples/status-message-collections/Cargo.lock, examples/status-message/Cargo.lock, examples/test-contract/Cargo.lock, examples/versioned/Cargo.lock, near-contract-standards/Cargo.toml, near-sdk-macros/Cargo.toml, near-sdk/Cargo.toml, near-sdk/src/store/lazy/mod.rs
Bit sneaky this slipped in, but added some checks to the CI to make sure this doesn't fail in the future
=> fix: Error const reference without default features

near-contract-standards/src/non_fungible_token/metadata.rs
Fixes #696
Weird formatting comes from cargo fmt
=> Added a default method for TokenMetadata

CODEOWNERS
=> chore: remove Austin from codeowners

near-sdk-macros/src/core_impl/abi/abi_generator.rs
=> fix: fully qualify the schema_container method call

CODEOWNERS
=> chore: add miraclx to codeowners

examples/fungible-token/ft/src/lib.rs
=> added ftmint event

README.md
=> updated readme to include rust contract standards info

near-sdk/src/promise.rs
Adds test coverage for `add_access_key` operations as requested in #516 .
=> test: add `add_access_key` test coverage

Cargo.toml, near-sdk/compilation_tests/all.rs, near-sdk/compilation_tests/schema_derive_invalids.stderr, near-sdk/src/collections/tree_map.rs, near-sdk/src/store/tree_map/mod.rs
@ruseinov I needed to unblock other PRs as well, so I took it from you ;-)
=> fix: Fixed compilation-tests after stable Rust release 1.72

near-sdk/Cargo.toml, near-sdk/src/environment/env.rs
Closes https://github.com/near/near-sdk-rs/issues/1051
=> random_seed_array documentation

near-sdk-macros/src/core_impl/info_extractor/arg_info.rs, near-sdk-macros/src/core_impl/info_extractor/item_impl_info.rs, near-sdk-macros/src/core_impl/info_extractor/item_trait_info.rs, near-sdk-macros/src/core_impl/utils/mod.rs, near-sdk/compilation_tests/bad_argument.stderr, near-sdk/compilation_tests/invalid_arg_pat.rs, near-sdk/compilation_tests/invalid_arg_pat.stderr
Closes https://github.com/near/near-sdk-rs/issues/1006
=>  Refactor info_extractor to accumulate compilation errors 

examples/mission-control/src/account.rs, examples/mission-control/src/asset.rs
I plan to also change all the build.sh scripts with [`cargo near build`](https://github.com/near/cargo-near)
=> feat: Updated examples to support NEAR ABI by default

.github/workflows/test.yml
=> [Fix] Downgrade clap dependency to match the toolchain.

examples/adder/Cargo.toml, examples/adder/src/lib.rs, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml
Closes https://github.com/near/near-sdk-rs/issues/1112
=> refactor: Cleanup re-exported packages

near-sdk/Cargo.toml, near-sdk/src/environment/mock/mocked_blockchain.rs, near-sdk/src/environment/mock/receipt.rs
* Updated dependencies for near-* packages to 0.23 version.
* Fixed compilation
=> chore: Updated near-* dependencies to 0.23

examples/adder/Cargo.toml, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.toml, examples/fungible-token/Cargo.toml, examples/lockable-fungible-token/Cargo.toml, examples/non-fungible-token/Cargo.toml
=> chore: bumped up near-workspaces in examples

.github/workflows/compare_sizes.yml
https://github.com/near/near-sdk-rs/actions/runs/11609101621
=> ci: replace `hub` with `gh` in compare-sizes.yml

examples/adder/Cargo.toml, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.toml, examples/fungible-token/Cargo.toml, examples/lockable-fungible-token/Cargo.toml, examples/mission-control/Cargo.toml, examples/non-fungible-token/Cargo.toml, examples/status-message/Cargo.toml, examples/test-contract/Cargo.toml, examples/versioned/Cargo.toml, near-sdk/Cargo.toml
=> chore: updates near-workspaces to 0.15 version

README.md
=> chore: updates readme badges to rust version 1.82

.github/workflows/test.yml, .github/workflows/test_examples.yml, .github/workflows/test_examples_small.yml
=> ci: bump rustcache @v1 -> @v2

near-sdk/Cargo.toml
=> chore!: updates near-* dependencies to 0.29 release

examples/adder/Cargo.toml, examples/callback-results/Cargo.toml, examples/cross-contract-calls/Cargo.toml, examples/factory-contract/Cargo.toml, examples/fungible-token/Cargo.toml, examples/lockable-fungible-token/Cargo.toml, examples/lockable-fungible-token/src/lib.rs, examples/mission-control/Cargo.toml, examples/non-fungible-token/Cargo.toml, examples/non-fungible-token/tests/workspaces/test_approval.rs, examples/status-message/Cargo.toml, examples/test-contract/Cargo.toml, examples/versioned/Cargo.toml, near-sdk/Cargo.toml
=> chore: updated near-workspaces in examples

near-sdk/src/lib.rs
this one is a small continuation on #1361
=> chore: expand cfgs' compilation error with complete reason of the error
